# Site settings
baseURL = "https://keshavasokan.netlify.app/"
languageCode = "en-us"
title = "CV Portfolio"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Keshav Asokan"
  description = "Data Science | Ex JP Morgan "

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  #[params.navigation]
    title = "Keshav Asokan"
    subtitle = "Aspiring Data Scientist "
    #menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "CV"
      url = "blogs/CV_KESHAV_ASOKAN_DATA MY.pdf"

    [[params.navigation.links]]
      name = "Get In Touch"
      url = "#"

    [[params.navigation.links]]
      name = "Social Media"
      url = "#"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    #[[params.navigation.button1]]
      #name = "Get Started"
      #url = "blogs"

    # Button Style 2
    #[[params.navigation.button2]]
      #name = "Log In"
      #url = "#"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
   title = "Hi, my name is Keshav"
    subtitle = "I'm interested in pursuing a career in data science."
    buttonText = "My Portfolio"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Alcohol Consumption Patterns"
      subtitle = "Trends in Beer, Wine & Spirits Examined"
      image = "projects/project1_image.png"
      url = "projects/project1"

    [[params.tiles.showcase]]
      title = "TFL Bike Ridership"
      subtitle = "Visualisation of Bike Usage"
      image = "projects/project2_image.png"
      url = "projects/project2"

    [[params.tiles.showcase]]
      title = "Covid-19"
      subtitle = "Do we know enough about this virus?"
      image = "projects/project3_image.png"
      url = "projects/project3"

    [[params.tiles.showcase]]
      title = "Brexit Refendrum"
      subtitle = "Did Political Affiliation affect Voting Patters?"
      image = "projects/project4_image.png"
      url = "projects/project4"
      
    [[params.tiles.showcase]]
      title = "Health Insurance"
      subtitle = "What are the factors affecting health insurance costs?"
      image = "projects/project4_image.png"
      url = "projects/project4"


    ##[[params.tiles.showcase]]
      #title = "Consequat"
      #subtitle = "Ipsum Dolor Sit Amet"
      #image = "pic05.jpg"
      #url = "blogs/ipsum"

   ## [[params.tiles.showcase]]
      #title = "Etiam"
      #subtitle = "Feugiat Amet Tempus"
      #image = "pic06.jpg"
      #url = "blogs/ipsum"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "About Me"
    subtitle = """Keshav Asokan is a student of Analytics and is very passionate about the use of data in business. He read Statistics, Economics and Finance at the University College London where he developed strong data analysis fundamentals. 
    Post graduation, he pursued employment in a major investment bank, J.P. Morgan as a graduate analyst. 
    Working in a data driven organsiation, Keshav learnt first hand on how data is able to empower organisations to make better decisions. He is currently seeking a data scientist position to complement his subject matter expertise in this area."""
    buttonText = "MY CV"
    url = "blogs/CV_KESHAV_ASOKAN_DATA MY.pdf"
    

  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    formEmail = "kasokan.mam2021@london.edu"
    
    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "kasokan.mam2021@london.edu"

    [[params.contact.phone]]
    title = "Phone"
    phone = "+6015 566 7869"

    [[params.contact.address]]
    title = "Address"
    street = "Regent's Park"
    city = "London, NW1 4SA"
    country = "United Kingdom"

  # Footer section
  [params.footer]
    enable = true
    copyright = "K.A"

    # Uses font awesome icons
    [[params.footer.social]]
      #icon = "fa-twitter"
      #url= "https://www.twitter.com"
      #label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/keshavasokan"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/keshavasokan"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com/keshavasokan"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/keshavasokan"
      label = "LinkedIn"

    [[params.footer.quicklinks]]
      text = "Design: "
      url= "https://www.html5up.net"
      alt = "HTML5 UP"
